version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/rebuilt
permissions:
  - object: /home/ec2-user/rebuilt
    owner: ec2-user
    group: ec2-user
    mode: 755
hooks:
  AfterInstall:
    - location: scripts/afterinstall.sh
  ApplicationStart:
    - location: scripts/applicationstart.sh
